# This file is a template...

stages:
  - controller
  - receiver
  - manifests

manager:
  stage: controller
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.6.0
    entrypoint: [""]
  script:
    - /busybox/echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_JOB_TOKEN\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE/controller:$CI_COMMIT_TAG

receiver:
  stage: receiver
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.6.0
    entrypoint: [""]
  script:
    - /busybox/echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_JOB_TOKEN\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.receive_adapter --destination $CI_REGISTRY_IMAGE/receive-adapter:$CI_COMMIT_TAG

manifests:
  stage: manifests
  image:
    name: gcr.io/triggermesh/kustomize
    entrypoint: [""]
  script:
    - kustomize build config/default > release.yaml
  artifacts:
    paths:
    - release.yaml
    