apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gitlabsources.sources.eventing.triggermesh.io
spec:
  group: sources.eventing.triggermesh.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: gitlabsources
    singular: gitlabsource
    kind: GitLabSource
    shortNames:
    - glsource
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
